/**
 * Curated White Lotus inspection checklist templates.
 *
 * These are transcribed verbatim from the official White Lotus QA/QC checklist
 * document. Only checklists transcribed with full accuracy are included here —
 * we deliberately do NOT bulk-import from the PDF's text layer because its
 * multi-line cells don't extract cleanly and would introduce errors.
 *
 * To add more: append an entry below (code must be unique) and re-run the
 * seed (POST /api/admin/seed-inspection-templates). Upsert by code, so it's
 * safe to run repeatedly.
 */

export type TemplateSeed = {
  code: string;
  name: string;
  activity?: string;
  module?: "QAQC" | "SAFETY";
  orderIndex: number;
  items: { seq: number; section?: string; description: string }[];
};

export const INSPECTION_TEMPLATES: TemplateSeed[] = [
  {
    code: "CL-QC-01",
    name: "Marking / Setting Out",
    activity: "MARKING",
    module: "QAQC",
    orderIndex: 1,
    items: [
      {
        seq: 1,
        description:
          "Checked and ensured approved GFC drawing with name, date and number of the drawing is available?",
      },
      {
        seq: 2,
        section: "Setting Out",
        description:
          "Check the approved site plans and setting out drawings for dimensional correctness and clarity",
      },
      { seq: 3, section: "Setting Out", description: "Has site been cleared and levelled as per requirement" },
      { seq: 4, section: "Setting Out", description: "Are the required tools and equipments available for marking" },
      {
        seq: 5,
        section: "Setting Out",
        description: "Calibration of the instruments are done and dates are valid at the time of using",
      },
      {
        seq: 6,
        section: "Setting Out",
        description: "TBM's are established and cross checked from the permanent bench marks",
      },
      { seq: 7, section: "Setting Out", description: "Are all set back distances as per setting out drawing, if any" },
      { seq: 8, section: "Setting Out", description: "Are all set back pillars at the same level, if any" },
      {
        seq: 9,
        section: "Setting Out",
        description:
          "Spacing between two consecutive pillars (if any) is restricted to a lesser distance to avoid tape sagging errors and control on grid pillars",
      },
      { seq: 10, section: "Setting Out", description: "Ensured the marking pillars are constructed rigid and safe" },
      {
        seq: 11,
        section: "Setting Out",
        description: "Ensured a layer of PCC as levelling course is done for marking the pillars",
      },
      {
        seq: 12,
        section: "Setting Out",
        description: "Ensured step down pillars for the sloping ground as directed by the client representative",
      },
      {
        seq: 13,
        section: "Setting Out",
        description: "Ensured grid lines of the pillars are marked almost at the centre of the pillar",
      },
      {
        seq: 14,
        section: "Setting Out",
        description: "Ensured the name of the grid pillar has been painted on the marking pillar",
      },
      {
        seq: 15,
        section: "Setting Out",
        description: "Ensured the thickness of the marking line is of the same thickness on the pillar",
      },
      {
        seq: 16,
        section: "Setting Out",
        description: "Ensured marking pillars are plastered, white washed, barricaded and protected",
      },
      {
        seq: 17,
        section: "Setting Out",
        description: "Ensured traverse closing and setting out are cross checked by PMC / Consultants",
      },
      {
        seq: 18,
        section: "Setting Out",
        description:
          "Set backs are checked and verified by PMC / Client. Any deviations observed are informed to Structural / Architectural consultants for approval",
      },
      { seq: 19, section: "Post-Execution Checks", description: "Are the markings protected" },
      { seq: 20, section: "Post-Execution Checks", description: "Are the markings done as per the latest revised drawing" },
    ],
  },
  {
    code: "CL-QC-01A",
    name: "Marking · PCC / Footing / Column / Starter",
    activity: "MARKING",
    module: "QAQC",
    orderIndex: 2,
    items: [
      { seq: 1, description: "GFC drawing with name, date and number is available" },
      { seq: 2, section: "PCC Marking", description: "Ensured the gridlines that are transferred to the ground is as per drawing" },
      { seq: 3, section: "PCC Marking", description: "Ensured the dimensions of the area where PCC will be laid" },
      { seq: 4, section: "PCC Marking", description: "Ensured the PCC top level is marked with pegs" },
      { seq: 5, section: "Footing and Columns Marking", description: "Ensured the grid lines that are transferred are as per drawing in accuracy" },
      { seq: 6, section: "Footing and Columns Marking", description: "Ensured the column/footing marking done as per drawing in accuracy" },
      { seq: 7, section: "Footing and Columns Marking", description: "Ensured the column/footing marking diagonal measurements are as per calculation from the drawing" },
      { seq: 8, section: "Footing and Columns Marking", description: "Ensured the column/footing measurements from any already cast nearby column/footing" },
      { seq: 9, section: "Footing and Columns Marking", description: "Ensured the cement paste where marking is done is cured enough" },
      { seq: 10, section: "Starter Marking", description: "Ensured a proper right angle in good working condition is used while marking starters" },
      { seq: 11, section: "Starter Marking", description: "Ensured the diagonal measurements are verified and correct" },
      { seq: 12, section: "Starter Marking", description: "Ensured the peripheral columns are in correct plumb with respect to the lower levels" },
      { seq: 13, section: "Starter Marking", description: "Ensured the marking is done clear" },
      { seq: 14, section: "Starter Marking", description: "Ensured the starter that is fixed over marking is firm enough to hold the concrete and vibrations" },
    ],
  },
  {
    code: "CL-QC-02",
    name: "Excavation",
    activity: "EXCAVATION",
    module: "QAQC",
    orderIndex: 3,
    items: [
      { seq: 1, description: "Checked and ensured approved GFC drawing with name, date and number of the drawing is available" },
      { seq: 2, section: "Pre-Execution Checks", description: "Ensured QA & PE approved work method statement is available with the team" },
      { seq: 3, section: "Pre-Execution Checks", description: "Ground is inspected and soil investigation report is available" },
      { seq: 4, section: "Pre-Execution Checks", description: "TBM's have been erected and cross checked by consultant" },
      { seq: 5, section: "Pre-Execution Checks", description: "Approved vendor is doing the work" },
      { seq: 6, section: "Pre-Execution Checks", description: "All the earthwork vehicles are in good condition" },
      { seq: 7, section: "Pre-Execution Checks", description: "Access routes for men and machinery are planned" },
      { seq: 8, section: "Pre-Execution Checks", description: "Ramps and step cutting details (if any) are planned" },
      { seq: 9, section: "Pre-Execution Checks", description: "Location for storing the earth has been finalised" },
      { seq: 10, section: "Pre-Execution Checks", description: "Areas to be excavated are cross checked with reference from the grid pillars made by the concerned" },
      { seq: 11, section: "Pre-Execution Checks", description: "Approval from structural consultant is received to proceed" },
      { seq: 12, section: "Pre-Execution Checks", description: "Water table details, de-watering pumps are readily available" },
      { seq: 13, section: "Pre-Execution Checks", description: "Earth reinforcement techniques are clearly understood by the contractor from structural consultant's drawing" },
      { seq: 14, section: "Pre-Execution Checks", description: "All the materials procured are tested for required IS-standards and found satisfactory" },
      { seq: 15, section: "Checks During Execution", description: "Ensured the excavation being done as per the drawing provided" },
      { seq: 16, section: "Checks During Execution", description: "Minimum distance is ensured for the footings for the easy removal of shuttering boards" },
      { seq: 17, section: "Checks During Execution", description: "Excavation is monitored closely to avoid over excavation" },
      { seq: 18, section: "Checks During Execution", description: "Proper shoring is taken care during loose soil area excavation" },
      { seq: 19, section: "Checks During Execution", description: "Controlled blastings are conducted by a licensed and experienced contractor only" },
      { seq: 20, section: "Checks During Execution", description: "The last 50-100 mm is being done manually to avoid soil disturbance" },
      { seq: 21, section: "Checks During Execution", description: "Drilling holes have been made to insert rod as per requirement" },
      { seq: 22, section: "Checks During Execution", description: "Length of the rod has been cut as per drawing and inserted at the angle mentioned in the drawing" },
      { seq: 23, section: "Checks During Execution", description: "Inserted rods are grouted completely throughout their length and holding rigidly as per requirement" },
      { seq: 24, section: "Checks During Execution", description: "Layers of rod insertions are completed before going for next level excavation" },
      { seq: 25, section: "Checks During Execution", description: "Weld mesh is done as per drawing and ensured for proper overlaps and stiffness" },
      { seq: 26, section: "Checks During Execution", description: "Shotcrete is as per design and sprayed for the required thickness that is to be achieved" },
      { seq: 27, section: "Post-Execution Checks", description: "The excavated area is checked as per the drawing" },
      { seq: 28, section: "Post-Execution Checks", description: "The excavated area is safe and as per required detailings" },
    ],
  },
  {
    code: "CL-QC-02A",
    name: "Filling and Compaction",
    activity: "FILLING",
    module: "QAQC",
    orderIndex: 4,
    items: [
      { seq: 1, description: "Checked and ensured approved GFC drawing with name, date and number of the drawing is available" },
      { seq: 2, section: "Pre-Execution Checks", description: "Ensured QA & PE approved work method statement is available with the team" },
      { seq: 3, section: "Pre-Execution Checks", description: "Is the waterproofing work completed?" },
      { seq: 4, section: "Pre-Execution Checks", description: "Are all the required compaction machineries available?" },
      { seq: 5, section: "Pre-Execution Checks", description: "Filling soil has been tested and approved for fill" },
      { seq: 6, section: "Checks During Execution", description: "Compaction is being done layer by layer as per requirement" },
      { seq: 7, section: "Checks During Execution", description: "Is the field density as specified by the structural consultant" },
      { seq: 8, section: "Checks During Execution", description: "Ensured manual compaction is carried out for the constrained spaces if any" },
      { seq: 9, section: "Checks During Execution", description: "Proper compaction procedure is ensured" },
      { seq: 10, section: "Post-Execution Checks", description: "Is the level of filling achieved as per drawing" },
    ],
  },
  {
    code: "CL-QC-03",
    name: "Anti-Termite Treatment",
    activity: "ANTITERMITE",
    module: "QAQC",
    orderIndex: 5,
    items: [
      { seq: 1, description: "Checked and ensured approved GFC drawing with name, date and number of the drawing is available" },
      { seq: 2, section: "Pre-Execution Checks", description: "Ensured QA & PE approved work method statement is available with the team" },
      { seq: 3, section: "Pre-Execution Checks", description: "Ensured the materials brought to site are tested as per ITP and approved by QA & PE" },
      { seq: 4, section: "Pre-Execution Checks", description: "Ensured the area to be treated is levelled and well compacted" },
      { seq: 5, section: "Pre-Execution Checks", description: "Ensured that all the safety precautions have been taken" },
      { seq: 6, section: "Pre-Execution Checks", description: "The chemical and its method of application are conforming to IS 6313 Part 1, 2 and 3" },
      { seq: 7, section: "Pre-Execution Checks", description: "The required tools are available at site" },
      { seq: 8, section: "Checks During Execution", description: "Ensured the dosage of chemical is as per specification" },
      { seq: 9, section: "Checks During Execution", description: "Ensured the applicator is trained personnel in handling chemicals" },
      { seq: 10, section: "Checks During Execution", description: "Preliminary moistening on sandy soil and shallow cut of required depth for clayey soil is ensured" },
      { seq: 11, section: "Checks During Execution", description: "Ensured the chemical is being poured at specified interval and depths" },
      { seq: 12, section: "Checks During Execution", description: "Ensured the chemical is poured below PCC at specified interval and depth" },
      { seq: 13, section: "Checks During Execution", description: "Ensured the applicator is using all the required PPE" },
      { seq: 14, section: "Post-Execution Checks", description: "Ensured the applied areas are not exposed to sunlight for a long time" },
      { seq: 15, section: "Post-Execution Checks", description: "Ensured the required quantity is consumed as per coverage area" },
    ],
  },
  {
    code: "CL-QC-05",
    name: "Footing · Formwork",
    activity: "FORMWORK",
    module: "QAQC",
    orderIndex: 7,
    items: [
      { seq: 1, description: "Checked and ensured the availability of GFC drawing with name, date and number" },
      { seq: 2, section: "Pre-Execution Checks", description: "Ensured adequate quantities of shuttering materials are available" },
      { seq: 3, section: "Pre-Execution Checks", description: "Ensured formwork oil only is used, not waste oil or grease" },
      { seq: 4, section: "Pre-Execution Checks", description: "Ensured shuttering boards are cleaned thoroughly before use" },
      { seq: 5, section: "Pre-Execution Checks", description: "Ensured runners used are properly planed" },
      { seq: 6, section: "Pre-Execution Checks", description: "Ensured footing shuttering is fixed over the marking done on the PCC" },
      { seq: 7, section: "Pre-Execution Checks", description: "Ensured all shuttering corners are at right angle" },
      { seq: 8, section: "Pre-Execution Checks", description: "Ensured extra supports for footings of height more than 900 mm" },
      { seq: 9, section: "Pre-Execution Checks", description: "Ensured extra dowel holes if any found are properly closed to arrest the slurry coming through them" },
      { seq: 10, section: "Pre-Execution Checks", description: "Ensured the alignment is in line with the reference line (dori)" },
      { seq: 11, section: "Pre-Execution Checks", description: "Ensured the formwork is perfectly vertical and plumb" },
      { seq: 12, section: "Pre-Execution Checks", description: "Ensured the materials used for formwork are clean and free from damage and rust" },
      { seq: 13, section: "Pre-Execution Checks", description: "Ensured footing shuttering dimensions are as per drawing" },
      { seq: 14, section: "Checks During Execution", description: "Ensured the footing is rigid during concreting and maintains its shape and position" },
      { seq: 15, section: "Checks During Execution", description: "Ensured the reference line and level is marked and achieved" },
      { seq: 16, section: "Checks During Execution", description: "Ensured no slurry leaks while pouring concrete" },
      { seq: 17, section: "Checks During Execution", description: "Ensured boards are kept at the concrete levels" },
      { seq: 18, section: "Checks During Execution", description: "Ensured reference nails are driven on top of runners and cross checked after concreting for the column alignments" },
      { seq: 19, section: "Post-Execution Checks", description: "Ensured boards and surroundings are cleaned immediately after concreting" },
      { seq: 20, section: "Post-Execution Checks", description: "Ensured boards are deshuttered without damage and oiled / stacked immediately" },
      { seq: 21, section: "Post-Execution Checks", description: "Ensured damaged boards are not used and scrapped from site" },
    ],
  },
  {
    code: "CL-QC-06",
    name: "Column · Formwork",
    activity: "FORMWORK",
    module: "QAQC",
    orderIndex: 8,
    items: [
      { seq: 1, description: "Checked and ensured the availability of GFC drawing with name, date and number" },
      { seq: 2, section: "Pre-Execution Checks", description: "Ensured adequate quantities of shuttering materials are available" },
      { seq: 3, section: "Pre-Execution Checks", description: "Ensured formwork oil only is used, not waste oil or grease" },
      { seq: 4, section: "Pre-Execution Checks", description: "Ensured shuttering boards are cleaned thoroughly before use" },
      { seq: 5, section: "Pre-Execution Checks", description: "Ensured runners used are properly planed" },
      { seq: 6, section: "Pre-Execution Checks", description: "Ensured column boxing is fixed over the starters rigidly; also ensured the starter is cast with correct dimensions" },
      { seq: 7, section: "Pre-Execution Checks", description: "Ensured cover blocks are tied with column reinforcement" },
      { seq: 8, section: "Pre-Execution Checks", description: "Ensure column box is raised with proper staging around" },
      { seq: 9, section: "Pre-Execution Checks", description: "Ensured extra dowel holes and starter sides are covered with foam strip to arrest the slurry coming through them" },
      { seq: 10, section: "Pre-Execution Checks", description: "Ensured the alignment is in line with the reference line (dori)" },
      { seq: 11, section: "Pre-Execution Checks", description: "Ensured the formwork is perfectly vertical and plumb; all external columns are checked for their vertical alignment and their continuation from the lower floor" },
      { seq: 12, section: "Pre-Execution Checks", description: "Ensured the materials used for formwork are clean and free from damage and rust" },
      { seq: 13, section: "Pre-Execution Checks", description: "Ensured column box dimensions are as per drawing and controlled with enough required tie-rods and C clamps" },
      { seq: 14, section: "Checks During Execution", description: "Ensured the column box is rigid during concreting and maintains its shape and position" },
      { seq: 15, section: "Checks During Execution", description: "Ensured the reference line and level is marked and achieved" },
      { seq: 16, section: "Checks During Execution", description: "Ensured no slurry leaks while pouring concrete" },
      { seq: 17, section: "Checks During Execution", description: "Ensured column box is kept at the required concrete levels" },
      { seq: 18, section: "Checks During Execution", description: "Ensured reference nails are driven on top of runners and cross checked after concreting for the column alignments" },
      { seq: 19, section: "Post-Execution Checks", description: "Ensured column boxes and surroundings are cleaned immediately after concreting" },
      { seq: 20, section: "Post-Execution Checks", description: "Ensured column boxes are de-shuttered without damage and oiled / stacked immediately" },
      { seq: 21, section: "Post-Execution Checks", description: "Ensured damaged boxes are not used and scrapped from site" },
    ],
  },
  {
    code: "CL-QC-07",
    name: "Beam & Slab · Formwork",
    activity: "FORMWORK",
    module: "QAQC",
    orderIndex: 9,
    items: [
      { seq: 1, description: "Checked and ensured the availability of GFC drawing with name, date and number" },
      { seq: 2, section: "Pre-Execution Checks", description: "Ensured damaged and dented sheets, acro spans, etc., are not used" },
      { seq: 3, section: "Pre-Execution Checks", description: "Ensured the shuttering surface is clean" },
      { seq: 4, section: "Pre-Execution Checks", description: "Ensured the staging is resting on a rigid compacted or concreted surface" },
      { seq: 5, section: "Pre-Execution Checks", description: "Ensured the dimensions are as per specifications" },
      { seq: 6, section: "Pre-Execution Checks", description: "Ensured the runners are planed even" },
      { seq: 7, section: "Pre-Execution Checks", description: "Ensured the props and staging are perfectly vertical and plumb" },
      { seq: 8, section: "Pre-Execution Checks", description: "Ensured base plate is kept on a rigid surface" },
      { seq: 9, section: "Pre-Execution Checks", description: "Ensured corners of shuttering are at right angle" },
      { seq: 10, section: "Pre-Execution Checks", description: "Ensured acro spans are resting on the beam sides" },
      { seq: 11, section: "Pre-Execution Checks", description: "Ensured the dowel holes and other minor gaps are closed properly" },
      { seq: 12, section: "Pre-Execution Checks", description: "Ensured complete cleaning inside beam bottom and column-beam junction" },
      { seq: 13, section: "Pre-Execution Checks", description: "Ensured the sheet / ply joints are closed with brown tapes" },
      { seq: 14, section: "Pre-Execution Checks", description: "Ensured minimum bearing for the cup locks, acro spans and other shuttering materials is followed" },
      { seq: 15, section: "Pre-Execution Checks", description: "Ensured the beam sides and slab level are perfectly vertical and levelled horizontally" },
      { seq: 16, section: "Pre-Execution Checks", description: "Ensured the external line of formwork is maintained using line-dori" },
      { seq: 17, section: "Pre-Execution Checks", description: "Ensure the top level of formwork is checked with 1 meter marking and as per specifications" },
      { seq: 18, section: "Pre-Execution Checks", description: "Ensured tie rods are provided for beam depths exceeding 600 mm" },
      { seq: 19, section: "Pre-Execution Checks", description: "Ensured all MEP cut-outs placed in sunken areas before fixing the beam side shuttering around the periphery and in structural drop locations" },
      { seq: 20, section: "Checks During Execution", description: "Ensured the slab and beam are in the same level and line during concreting" },
      { seq: 21, section: "Checks During Execution", description: "Ensured the reference line and level is marked and achieved" },
      { seq: 22, section: "Checks During Execution", description: "Ensured no slurry leaks while pouring concrete" },
      { seq: 23, section: "Checks During Execution", description: "Ensured cover blocks kept are not slipped and maintain required cover all the time during concreting" },
      { seq: 24, section: "Checks During Execution", description: "Ensured reference nails are driven on top of runners and cross checked after concreting for the column alignments" },
      { seq: 25, section: "Checks During Execution", description: "Ensured the level is as per drawing" },
      { seq: 26, section: "Post-Execution Checks", description: "Ensured the slab outer side, inside staging, column sides and slab floor are completely cleaned immediately" },
      { seq: 27, section: "Post-Execution Checks", description: "Ensured de-shuttering of beam sides is done only after 24 hrs and free from damages while de-shuttering" },
      { seq: 28, section: "Post-Execution Checks", description: "Ensured damaged and dented boards are scrapped and removed from site" },
    ],
  },
  {
    code: "CL-QC-08",
    name: "Retaining Walls, RCC Walls & Others (Lintel, Plinth Beam, Staircase) · Formwork",
    activity: "FORMWORK",
    module: "QAQC",
    orderIndex: 10,
    items: [
      { seq: 1, description: "Checked and ensured the availability of GFC drawing with name, date and number" },
      { seq: 2, section: "Pre-Execution Checks", description: "Ensured the shuttering surfaces are kept clean" },
      { seq: 3, section: "Pre-Execution Checks", description: "Ensured the runners used are planed properly" },
      { seq: 4, section: "Pre-Execution Checks", description: "Ensured the corner shuttering is at right angle" },
      { seq: 5, section: "Pre-Execution Checks", description: "Ensured the gauge rods and cover blocks are inserted" },
      { seq: 6, section: "Pre-Execution Checks", description: "Ensured the formwork is perfectly vertical and plumb" },
      { seq: 7, section: "Pre-Execution Checks", description: "Ensured the external line of formwork is maintained using a nylon thread" },
      { seq: 8, section: "Pre-Execution Checks", description: "Ensured top level of formwork is checked with respect to 1 meter marking" },
      { seq: 9, section: "Pre-Execution Checks", description: "Ensured proper support from bottom and sides for the plinth beams" },
      { seq: 10, section: "Pre-Execution Checks", description: "Ensured the dowel holes and the gaps around column (foam strip) are covered to avoid slurries coming out through the gaps" },
      { seq: 11, section: "Checks During Execution", description: "Ensured the supports and alignment are maintained during pour" },
      { seq: 12, section: "Checks During Execution", description: "Ensured the reference line and level is marked and achieved" },
      { seq: 13, section: "Checks During Execution", description: "Ensured no slurry leaks while pouring concrete" },
      { seq: 14, section: "Checks During Execution", description: "Ensured cover blocks kept are not slipped and maintain required cover all the time during concreting" },
      { seq: 15, section: "Checks During Execution", description: "Ensured reference nails are driven on top of runners and cross checked after concreting for the column alignments" },
      { seq: 16, section: "Checks During Execution", description: "Ensured the level is as per drawing" },
      { seq: 17, section: "Post-Execution Checks", description: "Ensured the line is maintained as per requirement" },
      { seq: 18, section: "Post-Execution Checks", description: "Ensured material is de-shuttered after attaining its strength" },
      { seq: 19, section: "Post-Execution Checks", description: "Ensured the board is de-shuttered carefully without damaging it and oiled / stacked neatly in place" },
      { seq: 20, section: "Post-Execution Checks", description: "Ensured damaged boards are scrapped and removed from site" },
    ],
  },
  {
    code: "CL-QC-09",
    name: "Footing · Reinforcement",
    activity: "REINFORCEMENT",
    module: "QAQC",
    orderIndex: 11,
    items: [
      { seq: 1, description: "Checked and ensured the availability of GFC drawing with name, date and number" },
      { seq: 2, section: "Pre-Execution Checks", description: "Ensured QA & PE approved work method statement is available with the team" },
      { seq: 3, section: "Pre-Execution Checks", description: "Checked and ensured the area is prepared for starting reinforcement (PCC complete)" },
      { seq: 4, section: "Pre-Execution Checks", description: "Checked and ensured the steel bars are tested and approved as per ITP" },
      { seq: 5, section: "Pre-Execution Checks", description: "Checked and ensured necessary barricading and safety measures are taken" },
      { seq: 6, section: "Pre-Execution Checks", description: "Checked and ensured required tools are available at the site" },
      { seq: 7, section: "Pre-Execution Checks", description: "Checked and ensured reinforcement is free from oil, mud, grease and other forms of contamination" },
      { seq: 8, section: "Checks During Execution", description: "Checked and ensured the reinforcement placing is done as per drawing" },
      { seq: 9, section: "Checks During Execution", description: "Ensured the column bars are placed as per GFC drawings with provision for alternate lap zone" },
      { seq: 10, section: "Checks During Execution", description: "Checked and ensured the spacing between the stirrups and the total number of stirrups are as per design" },
      { seq: 11, section: "Checks During Execution", description: "Ensured the anchors are provided as per drawings at the edges of the footing" },
      { seq: 12, section: "Checks During Execution", description: "Ensured the chairs are provided at appropriate locations and as per design" },
      { seq: 13, section: "Checks During Execution", description: "Ensured the cover blocks are of correct sizes and at correct spacing" },
      { seq: 14, section: "Checks During Execution", description: "Ensured the development lengths and anchorage lengths provided are as per drawings" },
      { seq: 15, section: "Checks During Execution", description: "Ensured the dowels provided for future concreting are as per drawings" },
      { seq: 16, section: "Post-Execution Checks", description: "Ensured the reinforcements are clean and free from any unwanted materials" },
      { seq: 17, section: "Post-Execution Checks", description: "Ensured the reinforcements are tied properly with binding wire of necessary gauge" },
      { seq: 18, section: "Post-Execution Checks", description: "Ensured no bars are twisted or deformed in any manner" },
      { seq: 19, section: "Post-Execution Checks", description: "Ensured the position of reinforcement and chairs are not disturbed" },
    ],
  },
  {
    code: "CL-QC-10",
    name: "Column · Reinforcement",
    activity: "REINFORCEMENT",
    module: "QAQC",
    orderIndex: 12,
    items: [
      { seq: 1, description: "Checked and ensured the availability of GFC drawing with name, date and number" },
      { seq: 2, section: "Pre-Execution Checks", description: "Ensured QA & PE approved work method statement is available with the team" },
      { seq: 3, section: "Pre-Execution Checks", description: "Checked and ensured the area is prepared for starting reinforcement (PCC complete / slab concrete set)" },
      { seq: 4, section: "Pre-Execution Checks", description: "Checked and ensured the steel bars are tested and approved as per ITP" },
      { seq: 5, section: "Pre-Execution Checks", description: "Checked and ensured availability of necessary scaffolding and safety measures are taken" },
      { seq: 6, section: "Pre-Execution Checks", description: "Checked and ensured required tools are available at the site" },
      { seq: 7, section: "Pre-Execution Checks", description: "Checked and ensured reinforcement is free from oil, mud, grease and other forms of contamination" },
      { seq: 8, section: "Checks During Execution", description: "Ensured the column bars are placed as per GFC drawings with provision for alternate lap zone" },
      { seq: 9, section: "Checks During Execution", description: "Checked and ensured the spacing between the stirrups and the total number of stirrups are as per design" },
      { seq: 10, section: "Checks During Execution", description: "Ensured stirrups are provided up to the bottom of each footing and at the beam-column junction" },
      { seq: 11, section: "Checks During Execution", description: "Ensured that the reinforcement bars projecting out of the current area of concreting are parallel" },
      { seq: 12, section: "Checks During Execution", description: "Ensured the cover blocks are of correct sizes and at correct spacing" },
      { seq: 13, section: "Checks During Execution", description: "Ensured a minimum of three stirrups are done above the concrete finishing level to maintain the shape of the reinforcement" },
      { seq: 14, section: "Checks During Execution", description: "Ensured adequate anchorage lengths are provided at the bottom of the column reinforcement" },
      { seq: 15, section: "Checks During Execution", description: "Ensured the provision of dowels for future extensions is done as per the drawings" },
      { seq: 16, section: "Checks During Execution", description: "Ensured the ends of the dowels for future extension are covered properly with polythene sheets" },
      { seq: 17, section: "Post-Execution Checks", description: "Ensured the reinforcements are clean and free from any unwanted materials" },
      { seq: 18, section: "Post-Execution Checks", description: "Ensured the reinforcements are tied properly with binding wire of necessary gauge" },
      { seq: 19, section: "Post-Execution Checks", description: "Ensured no bars are twisted or deformed in any manner" },
      { seq: 20, section: "Post-Execution Checks", description: "Ensured the position of reinforcement and stirrups are not disturbed" },
    ],
  },
  {
    code: "CL-QC-11",
    name: "Beam & Slab · Reinforcement",
    activity: "REINFORCEMENT",
    module: "QAQC",
    orderIndex: 13,
    items: [
      { seq: 1, description: "Checked and ensured the availability of GFC drawing with name, date and number" },
      { seq: 2, section: "Pre-Execution Checks", description: "Ensured QA & PE approved work method statement is available with the team" },
      { seq: 3, section: "Pre-Execution Checks", description: "Ensured the shuttering works are completed and mould release agents are applied" },
      { seq: 4, section: "Pre-Execution Checks", description: "Checked and ensured the steel bars are tested and approved as per ITP" },
      { seq: 5, section: "Pre-Execution Checks", description: "Checked and ensured barricading and safety measures are taken" },
      { seq: 6, section: "Pre-Execution Checks", description: "Checked and ensured required tools are available at the site" },
      { seq: 7, section: "Pre-Execution Checks", description: "Checked and ensured reinforcement is free from oil, mud, grease and other forms of contamination" },
      { seq: 8, section: "Checks During Execution", description: "Ensured the reinforcement is done as per GFC drawings" },
      { seq: 9, section: "Checks During Execution", description: "Ensured cover blocks kept are not slipped and maintain required cover all the time during concreting" },
      { seq: 10, section: "Checks During Execution", description: "Ensured no slurry leaks while pouring concrete" },
      { seq: 11, section: "Checks During Execution", description: "Ensured chairs and spacers are provided at required intervals to maintain top and bottom reinforcement positioning" },
      { seq: 12, section: "Checks During Execution", description: "Ensured reference nails are driven on top of runners and cross checked after concreting for the column alignments" },
      { seq: 13, section: "Checks During Execution", description: "Ensured the level is as per drawing" },
      { seq: 14, section: "Post-Execution Checks", description: "Ensured the reinforcements are clean and free from any unwanted materials" },
      { seq: 15, section: "Post-Execution Checks", description: "Ensured the reinforcements are tied properly with binding wire of necessary gauge" },
      { seq: 16, section: "Post-Execution Checks", description: "Ensured no bars are twisted or deformed in any manner" },
    ],
  },
  {
    code: "CL-QC-12",
    name: "Retaining Walls, RCC Walls & Others (Lintel, Plinth Beam, Staircase) · Reinforcement",
    activity: "REINFORCEMENT",
    module: "QAQC",
    orderIndex: 14,
    items: [
      { seq: 1, description: "Checked and ensured the availability of GFC drawing with name, date and number" },
      { seq: 2, section: "Pre-Execution Checks", description: "Ensured QA & PE approved work method statement is available with the team" },
      { seq: 3, section: "Pre-Execution Checks", description: "Checked and ensured the area is prepared for starting reinforcement (PCC complete / slab concrete set)" },
      { seq: 4, section: "Pre-Execution Checks", description: "Checked and ensured the steel bars are tested and approved as per ITP" },
      { seq: 5, section: "Pre-Execution Checks", description: "Checked and ensured availability of necessary scaffolding and safety measures are taken" },
      { seq: 6, section: "Pre-Execution Checks", description: "Checked and ensured required tools are available at the site" },
      { seq: 7, section: "Pre-Execution Checks", description: "Checked and ensured reinforcement is free from oil, mud, grease and other forms of contamination" },
      { seq: 8, section: "Checks During Execution", description: "Ensured the reinforcement bars are placed as per GFC drawings with provision for alternate lap zone" },
      { seq: 9, section: "Checks During Execution", description: "Ensured that the reinforcement bars projecting out of the current area of concreting are parallel" },
      { seq: 10, section: "Checks During Execution", description: "Ensured the cover blocks are of correct sizes and at correct spacing" },
      { seq: 11, section: "Checks During Execution", description: "Ensured adequate development and anchorage lengths are provided" },
      { seq: 12, section: "Checks During Execution", description: "Ensured the provision of dowels for future extensions is done as per the drawings" },
      { seq: 13, section: "Checks During Execution", description: "Ensured the ends of the dowels for future extension are covered properly with polythene sheets" },
      { seq: 14, section: "Post-Execution Checks", description: "Ensured the reinforcements are clean and free from any unwanted materials" },
      { seq: 15, section: "Post-Execution Checks", description: "Ensured the reinforcements are tied properly with binding wire of necessary gauge" },
      { seq: 16, section: "Post-Execution Checks", description: "Ensured no bars are twisted or deformed in any manner" },
      { seq: 17, section: "Post-Execution Checks", description: "Ensured the position of reinforcement bars is not disturbed" },
    ],
  },
  {
    code: "CL-QC-13",
    name: "Footing · Concreting",
    activity: "CONCRETING",
    module: "QAQC",
    orderIndex: 15,
    items: [
      { seq: 1, description: "Checked and ensured the availability of GFC drawing with name, date and number" },
      { seq: 2, section: "Pre-Execution Checks", description: "Ensured QA & PE approved work method statement is available with the team" },
      { seq: 3, section: "Pre-Execution Checks", description: "Ensured materials used in concrete are tested as per ITP and approved by QA & PE" },
      { seq: 4, section: "Pre-Execution Checks", description: "Checked and ensured all the shuttering and reinforcement works are completed and approved" },
      { seq: 5, section: "Pre-Execution Checks", description: "Checked and ensured MEP services are completed and approved" },
      { seq: 6, section: "Pre-Execution Checks", description: "Checked and ensured necessary barricading and safety measures are taken" },
      { seq: 7, section: "Pre-Execution Checks", description: "Checked and ensured required tools are available at the site" },
      { seq: 8, section: "Pre-Execution Checks", description: "Ensured sufficient manpower is available for concreting on site" },
      { seq: 9, section: "Pre-Execution Checks", description: "Ensured suitable vibrators, fuel and vibrator needles are employed for different members of a structure" },
      { seq: 10, section: "Pre-Execution Checks", description: "Ensured vibrators are in working condition and standby vibrators are available at site" },
      { seq: 11, section: "Pre-Execution Checks", description: "Ensured necessary cube moulds and slump cones are available at site" },
      { seq: 12, section: "Pre-Execution Checks", description: "Checked and ensured all the workers are wearing safety PPE" },
      { seq: 13, section: "Checks During Execution", description: "Checked and ensured the grade of concrete, mix ratio of materials mentioned in the batch ticket are as per approved design mix" },
      { seq: 14, section: "Checks During Execution", description: "Ensured the workability of the mix as per approved requirements" },
      { seq: 15, section: "Checks During Execution", description: "Checked and ensured pour cards are filled for every truck load of concrete" },
      { seq: 16, section: "Checks During Execution", description: "Ensured shuttering is wet and clean before concreting" },
      { seq: 17, section: "Checks During Execution", description: "Ensured layer-wise concreting followed with the height of a single layer of concrete not exceeding 1 m" },
      { seq: 18, section: "Checks During Execution", description: "Ensured the required number of concrete cubes are cast for testing at site" },
      { seq: 19, section: "Checks During Execution", description: "Ensured sufficient compaction is done properly" },
      { seq: 20, section: "Checks During Execution", description: "Ensured the concrete is finished within three hours from the time of mixing / as per design mix if retarders are used" },
      { seq: 21, section: "Checks During Execution", description: "Ensured the level of finish is checked and corrected when concrete is fresh" },
      { seq: 22, section: "Checks During Execution", description: "Ensured rough finish is done in the footing-column interface" },
      { seq: 23, section: "Checks During Execution", description: "Ensured any excess slurry is cleaned" },
      { seq: 24, section: "Post-Execution Checks", description: "Ensured deshuttering is done after the recommended stripping time" },
      { seq: 25, section: "Post-Execution Checks", description: "Ensured all tie rod holes are packed with approved grout" },
      { seq: 26, section: "Post-Execution Checks", description: "Ensured the surface of the concrete is good without any defects such as honeycombs, damages, etc." },
      { seq: 27, section: "Post-Execution Checks", description: "Ensured the dimensions, line, level and plumb are within limits and recorded post deshuttering" },
      { seq: 28, section: "Post-Execution Checks", description: "Ensured the date of casting is neatly marked on the surface" },
      { seq: 29, section: "Post-Execution Checks", description: "Ensured the curing of the concrete is done by covering the surface using hessian cloths or curing compounds" },
      { seq: 30, section: "Post-Execution Checks", description: "Ensured housekeeping is maintained around the cast area" },
    ],
  },
  {
    code: "CL-QC-14",
    name: "Column · Concreting",
    activity: "CONCRETING",
    module: "QAQC",
    orderIndex: 16,
    items: [
      { seq: 1, description: "Checked and ensured the availability of GFC drawing with name, date and number" },
      { seq: 2, section: "Pre-Execution Checks", description: "Ensured QA & PE approved work method statement is available with the team" },
      { seq: 3, section: "Pre-Execution Checks", description: "Ensured materials used in concrete are tested as per ITP and approved by QA & PE" },
      { seq: 4, section: "Pre-Execution Checks", description: "Checked and ensured all the shuttering and reinforcement works are completed and approved" },
      { seq: 5, section: "Pre-Execution Checks", description: "Ensured the verticality of the column box and that it is supported properly" },
      { seq: 6, section: "Pre-Execution Checks", description: "Checked and ensured necessary barricading and safety measures are taken" },
      { seq: 7, section: "Pre-Execution Checks", description: "Checked and ensured required tools are available at the site" },
      { seq: 8, section: "Pre-Execution Checks", description: "Ensured sufficient manpower is available for concreting on site" },
      { seq: 9, section: "Pre-Execution Checks", description: "Ensured suitable vibrators, fuel and vibrator needles are employed for different members of a structure" },
      { seq: 10, section: "Pre-Execution Checks", description: "Ensured vibrators are in working condition and standby vibrators are available at site" },
      { seq: 11, section: "Pre-Execution Checks", description: "Ensured necessary cube moulds and slump cones are available at site" },
      { seq: 12, section: "Pre-Execution Checks", description: "Checked and ensured all the workers are wearing safety PPE" },
      { seq: 13, section: "Checks During Execution", description: "Checked and ensured the grade of concrete, mix ratio of materials mentioned in the batch ticket are as per approved design mix" },
      { seq: 14, section: "Checks During Execution", description: "Ensured the workability of the mix as per approved requirements" },
      { seq: 15, section: "Checks During Execution", description: "Ensured shuttering is wet and clean before concreting" },
      { seq: 16, section: "Checks During Execution", description: "Ensured layer-wise concreting followed with the height of a single layer of concrete not exceeding 1 m" },
      { seq: 17, section: "Checks During Execution", description: "Ensured the required number of concrete cubes are cast for testing at site" },
      { seq: 18, section: "Checks During Execution", description: "Ensured sufficient compaction is done properly" },
      { seq: 19, section: "Checks During Execution", description: "Ensured the concrete is finished within three hours from the time of mixing / as per design mix if retarders are used" },
      { seq: 20, section: "Checks During Execution", description: "Ensured the top level of concrete and verticality is checked and corrected" },
      { seq: 21, section: "Checks During Execution", description: "Ensured any excess slurry is cleaned" },
      { seq: 22, section: "Post-Execution Checks", description: "Ensured deshuttering is done after the recommended stripping time" },
      { seq: 23, section: "Post-Execution Checks", description: "Ensured all tie rod holes are packed with approved grout" },
      { seq: 24, section: "Post-Execution Checks", description: "Ensured the surface of the concrete is good without any defects such as honeycombs, damages, etc." },
      { seq: 25, section: "Post-Execution Checks", description: "Ensured the dimensions, line, level and plumb are within limits and recorded post deshuttering" },
      { seq: 26, section: "Post-Execution Checks", description: "Ensured the date of casting is neatly marked on the surface" },
      { seq: 27, section: "Post-Execution Checks", description: "Ensured the curing of the concrete is done by covering the surface using hessian cloths or curing compounds" },
      { seq: 28, section: "Post-Execution Checks", description: "Ensured housekeeping is maintained around the cast area" },
    ],
  },
  {
    code: "CL-QC-15",
    name: "Beam & Slab · Concreting",
    activity: "CONCRETING",
    module: "QAQC",
    orderIndex: 17,
    items: [
      { seq: 1, description: "Checked and ensured the availability of GFC drawing with name, date and number" },
      { seq: 2, section: "Pre-Execution Checks", description: "Ensured QA & PE approved work method statement is available with the team" },
      { seq: 3, section: "Pre-Execution Checks", description: "Ensured materials used in concrete are tested as per ITP and approved by QA & PE" },
      { seq: 4, section: "Pre-Execution Checks", description: "Checked and ensured all the shuttering and reinforcement works are completed and approved" },
      { seq: 5, section: "Pre-Execution Checks", description: "Checked and ensured MEP services are completed and approved" },
      { seq: 6, section: "Pre-Execution Checks", description: "Checked and ensured necessary barricading and safety measures are taken" },
      { seq: 7, section: "Pre-Execution Checks", description: "Checked and ensured required tools are available at the site" },
      { seq: 8, section: "Pre-Execution Checks", description: "Ensured sufficient manpower is available for concreting on site" },
      { seq: 9, section: "Pre-Execution Checks", description: "Ensured suitable vibrators, fuel and vibrator needles are employed for different members of a structure" },
      { seq: 10, section: "Pre-Execution Checks", description: "Ensured vibrators are in working condition and standby vibrators are available at site" },
      { seq: 11, section: "Pre-Execution Checks", description: "Ensured markings are made on the column dowels for concrete level" },
      { seq: 12, section: "Pre-Execution Checks", description: "Ensured necessary cube moulds and slump cones are available at site" },
      { seq: 13, section: "Pre-Execution Checks", description: "Checked and ensured all the workers are wearing safety PPE" },
      { seq: 14, section: "Checks During Execution", description: "Checked and ensured the grade of concrete, mix ratio of materials mentioned in the batch ticket are as per approved design mix" },
      { seq: 15, section: "Checks During Execution", description: "Ensured the workability of the mix as per approved requirements" },
      { seq: 16, section: "Checks During Execution", description: "Ensured pour cards are filled for every truck load of concrete" },
      { seq: 17, section: "Checks During Execution", description: "Ensured shuttering is wet and clean before concreting" },
      { seq: 18, section: "Checks During Execution", description: "Ensured layer-wise concreting is followed for depths of concreting more than 500 mm" },
      { seq: 19, section: "Checks During Execution", description: "Ensured the required number of concrete cubes are cast for testing at site" },
      { seq: 20, section: "Checks During Execution", description: "Ensured sufficient compaction is done properly" },
      { seq: 21, section: "Checks During Execution", description: "Ensured the concrete is finished within three hours from the time of mixing / as per design mix if retarders are used" },
      { seq: 22, section: "Checks During Execution", description: "Ensured the level of finish is checked and corrected when concrete is fresh" },
      { seq: 23, section: "Checks During Execution", description: "Ensured any excess slurry is cleaned" },
      { seq: 24, section: "Post-Execution Checks", description: "Ensured deshuttering is done after the recommended stripping time" },
      { seq: 25, section: "Post-Execution Checks", description: "Ensured all tie rod holes are packed with approved grout" },
      { seq: 26, section: "Post-Execution Checks", description: "Ensured the surface of the concrete is good without any defects such as honeycombs, damages, etc." },
      { seq: 27, section: "Post-Execution Checks", description: "Ensured the dimensions, line, level and plumb are within limits and recorded post deshuttering" },
      { seq: 28, section: "Post-Execution Checks", description: "Ensured the date of casting is neatly marked on the surface" },
      { seq: 29, section: "Post-Execution Checks", description: "Ensured the curing of the concrete is done by covering the surface using hessian cloths or curing compounds" },
      { seq: 30, section: "Post-Execution Checks", description: "Ensured housekeeping is maintained around the cast area" },
    ],
  },
  {
    code: "CL-QC-16",
    name: "Retaining Walls, RCC Walls & Others (Lintel, Plinth Beam, Staircase) · Concreting",
    activity: "CONCRETING",
    module: "QAQC",
    orderIndex: 18,
    items: [
      { seq: 1, description: "Checked and ensured the availability of GFC drawing with name, date and number" },
      { seq: 2, section: "Pre-Execution Checks", description: "Ensured QA & PE approved work method statement is available with the team" },
      { seq: 3, section: "Pre-Execution Checks", description: "Ensured materials used in concrete are tested as per ITP and approved by QA & PE" },
      { seq: 4, section: "Pre-Execution Checks", description: "Checked and ensured all the shuttering and reinforcement works are completed and approved" },
      { seq: 5, section: "Pre-Execution Checks", description: "Ensured the verticality of the shuttering and that it is supported properly" },
      { seq: 6, section: "Pre-Execution Checks", description: "Checked and ensured necessary barricading and safety measures are taken" },
      { seq: 7, section: "Pre-Execution Checks", description: "Checked and ensured required tools are available at the site" },
      { seq: 8, section: "Pre-Execution Checks", description: "Ensured sufficient manpower is available for concreting on site" },
      { seq: 9, section: "Pre-Execution Checks", description: "Ensured suitable vibrators, fuel and vibrator needles are employed for different members of a structure" },
      { seq: 10, section: "Pre-Execution Checks", description: "Ensured vibrators are in working condition and standby vibrators are available at site" },
      { seq: 11, section: "Pre-Execution Checks", description: "Ensured necessary cube moulds and slump cones are available at site" },
      { seq: 12, section: "Pre-Execution Checks", description: "Checked and ensured all the workers are wearing safety PPE" },
      { seq: 13, section: "Checks During Execution", description: "Checked and ensured the grade of concrete, mix ratio of materials mentioned in the batch ticket are as per approved design mix" },
      { seq: 14, section: "Checks During Execution", description: "Ensured the workability of the mix as per approved requirements" },
      { seq: 15, section: "Checks During Execution", description: "Ensured pour cards are filled for every truck load of concrete" },
      { seq: 16, section: "Checks During Execution", description: "Ensured shuttering is wet and clean before concreting" },
      { seq: 17, section: "Checks During Execution", description: "Ensured layer-wise concreting followed with the height of a single layer of concrete not exceeding 1 m" },
      { seq: 18, section: "Checks During Execution", description: "Ensured the required number of concrete cubes are cast for testing at site" },
      { seq: 19, section: "Checks During Execution", description: "Ensured sufficient compaction is done properly" },
      { seq: 20, section: "Checks During Execution", description: "Ensured the concrete is finished within three hours from the time of mixing / as per design mix if retarders are used" },
      { seq: 21, section: "Checks During Execution", description: "Ensured the top level of concrete and verticality is checked and corrected" },
      { seq: 22, section: "Checks During Execution", description: "Ensured any excess slurry is cleaned" },
      { seq: 23, section: "Post-Execution Checks", description: "Ensured deshuttering is done after the recommended stripping time" },
      { seq: 24, section: "Post-Execution Checks", description: "Ensured all tie rod holes are packed with approved grout" },
      { seq: 25, section: "Post-Execution Checks", description: "Ensured the surface of the concrete is good without any defects such as honeycombs, damages, etc." },
      { seq: 26, section: "Post-Execution Checks", description: "Ensured the dimensions, line, level and plumb are within limits and recorded post deshuttering" },
      { seq: 27, section: "Post-Execution Checks", description: "Ensured the date of casting is neatly marked on the surface" },
      { seq: 28, section: "Post-Execution Checks", description: "Ensured the curing of the concrete is done by covering the surface using hessian cloths or curing compounds" },
      { seq: 29, section: "Post-Execution Checks", description: "Ensured housekeeping is maintained around the cast area" },
    ],
  },
  {
    code: "CL-QC-04",
    name: "PCC (Plain Cement Concrete)",
    activity: "PCC",
    module: "QAQC",
    orderIndex: 6,
    items: [
      { seq: 1, description: "Checked and ensured the availability of GFC drawing with name, date and number" },
      { seq: 2, section: "Pre-Execution Checks", description: "Ensured QA & PE approved work method statement is available with the team" },
      { seq: 3, section: "Pre-Execution Checks", description: "Ensured materials used in concrete are tested as per ITP and approved by QA & PE" },
      { seq: 4, section: "Pre-Execution Checks", description: "Checked and ensured necessary barricading and safety measures are taken" },
      { seq: 5, section: "Pre-Execution Checks", description: "Checked and ensured required tools are available at the site" },
      { seq: 6, section: "Pre-Execution Checks", description: "Ensured sufficient manpower is available for concreting on site" },
      { seq: 7, section: "Pre-Execution Checks", description: "Ensured the dimensions and orientation of the excavated pit have been checked" },
      { seq: 8, section: "Pre-Execution Checks", description: "Ensured the excavated pit is cleaned and no water stagnation is found" },
      { seq: 9, section: "Pre-Execution Checks", description: "Ensured the excavated pit is watered and rammed for better compaction strata" },
      { seq: 10, section: "Pre-Execution Checks", description: "Ensured necessary side shuttering is complete and in place" },
      { seq: 11, section: "Pre-Execution Checks", description: "Ensured anti-termite works are done half an hour before starting of PCC" },
      { seq: 12, section: "Checks During Execution", description: "Checked and ensured the grade of concrete, mix ratio of materials mentioned in the batch ticket are as per approved design mix" },
      { seq: 13, section: "Checks During Execution", description: "Ensured the labourers are wearing gum boots while concreting" },
      { seq: 14, section: "Checks During Execution", description: "Ensured the PCC level is checked and corrected when concrete is fresh" },
      { seq: 15, section: "Checks During Execution", description: "Ensured any excess slurry is cleaned" },
      { seq: 16, section: "Post-Execution Checks", description: "Ensured deshuttering is done after the recommended stripping time" },
      { seq: 17, section: "Post-Execution Checks", description: "Ensured the surface of the concrete is good without any defects such as honeycombs, damages, etc." },
      { seq: 18, section: "Post-Execution Checks", description: "Ensured the date of casting is neatly marked on the surface" },
      { seq: 19, section: "Post-Execution Checks", description: "Ensured the curing of the concrete is done by covering the surface using hessian cloths or curing compounds" },
      { seq: 20, section: "Post-Execution Checks", description: "Ensured housekeeping is maintained around the cast area" },
    ],
  },
];
